// ============================================================================
//  model.h  -  AUTO-GENERATED by src/export_embedded.py. Do not edit by hand;
//  retrain and re-export instead.
// ============================================================================
//  Model:        decision_tree
//  Data kind:    REAL
//  Trained at:   2026-10-02T10:41:55
//  Exported at:  2026-10-02T10:43:22
//  Training rows: 504   Test rows: 216
//  Features (order): moisture_pct, temperature_c, humidity_pct
//  Output: true = WATER, false = NO_WATER
//
//  Pure C/C++ with no Arduino dependencies, so it also compiles on a PC
//  (used by the Python-vs-C consistency check).
// ============================================================================

#ifndef SMART_IRRIGATION_MODEL_H
#define SMART_IRRIGATION_MODEL_H

#define MODEL_IS_DEMO 0
#define MODEL_NAME "decision_tree"
#define MODEL_SOIL_FEATURE_IS_PCT 1

// ---- Soil calibration (from the config used for training) ----
// raw == SOIL_RAW_DRY -> 0 %,  raw == SOIL_RAW_WET -> 100 %, linear, clipped.
static const float SOIL_RAW_DRY = 620.0f;
static const float SOIL_RAW_WET = 270.0f;

static inline float soilRawToMoisturePct(float soilRaw) {
    // Same float32 operations, in the same order, as preprocessing.raw_to_moisture_pct
    float pct = (SOIL_RAW_DRY - soilRaw) / (SOIL_RAW_DRY - SOIL_RAW_WET) * 100.0f;
    if (pct < 0.0f) pct = 0.0f;
    if (pct > 100.0f) pct = 100.0f;
    return pct;
}

// soilMoisturePct: calibrated soil moisture in %
static inline bool needsWater(float soilMoisturePct, float temperatureC, float humidityPct) {
    (void)humidityPct;  // not used by this model
    // check moisture_pct (split learned from 504 training samples)
    if (soilMoisturePct <= 33.0f) {
        // check temperature_c (split learned from 199 training samples)
        if (temperatureC <= 22.5999985f) {
            // check moisture_pct (split learned from 49 training samples)
            if (soilMoisturePct <= 29.5714283f) {
                return true;  // WATER (32 training samples)
            } else {
                return false;  // NO_WATER (17 training samples)
            }
        } else {
            return true;  // WATER (150 training samples)
        }
    } else {
        // check moisture_pct (split learned from 305 training samples)
        if (soilMoisturePct <= 43.2857132f) {
            // check temperature_c (split learned from 103 training samples)
            if (temperatureC <= 30.2999992f) {
                return false;  // NO_WATER (62 training samples)
            } else {
                return true;  // WATER (41 training samples)
            }
        } else {
            return false;  // NO_WATER (202 training samples)
        }
    }
}

// Convenience wrapper: raw ADC value -> same preprocessing as training -> decision.
static inline bool needsWaterFromRaw(int soilRaw, float temperatureC, float humidityPct) {
    return needsWater(soilRawToMoisturePct((float)soilRaw), temperatureC, humidityPct);
}

#endif  // SMART_IRRIGATION_MODEL_H
